<?php
$data = array (
  491 => 
  array (
    'cat_id' => '491',
    'cat_name' => '饮料系列',
    'cat_ico' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '491',
    'name' => '饮料系列',
  ),
  492 => 
  array (
    'cat_id' => '492',
    'cat_name' => '保健品类',
    'cat_ico' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '492',
    'name' => '保健品类',
  ),
  493 => 
  array (
    'cat_id' => '493',
    'cat_name' => '家用系列',
    'cat_ico' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '493',
    'name' => '家用系列',
  ),
);
?>